### ISSUE TITLE
workspace_1.toFileName is not a function

### ISSUE THREAD

**Issue by mikerudge** [myin142/myin-tools#1]
Hey 

I am getting `workspace_1.toFileName is not a function` when running `nx g @myin/aws-cdk:application [appName]`

Just wanted to let you know!

**Comment by myin142** [comment]
Thanks, I will try to look into it when I have some time.

But it might be helpful to have the full error stacktrace if available and a sample project or at least the package.json

**Comment by Gvozdik-Darya** [comment]
My steps: 
npx create-nx-workspace@latest 'name'
cd 'name'
npm install --save-dev @myin/aws-cdk
npx nx g @myin/aws-cdk:application 'project-name'
get error
![Снимок экрана от 2022-02-11 15-11-27](https://user-images.githubusercontent.com/74375483/153597666-d0403b3a-820a-4fca-9401-5d7e933b4157.png)

**Comment by myin142** [comment]
It should work now if you use version `>= 0.0.11` with nx workspace v13. Let me know if this fixed the issue, then I can close it.

**Comment by Gvozdik-Darya** [comment]
After nx g @myin/aws-cdk:application [appName] -> Project was generated successfully. Thanks)
